### ISSUE TITLE
Dude `npm install webgpu-sky-atmosphre?`

### ISSUE THREAD

**Issue by lawwantsin** [JolifantoBambla/webgpu-sky-atmosphere#6]
This is a great piece of software.
![Screenshot 2024-10-25 at 5 39 37 PM](https://github.com/user-attachments/assets/a45909b4-573e-4bc4-9dc1-4b828213fc5a)
Please fix.  Mad love.

**Comment by JolifantoBambla** [comment]
Oh man, I can't type - thanks for reporting!

Fixed in 8a432e6
